language: objective-c
install:
- scripts/install_sdl.sh
- scripts/bootstrap.sh
- scripts/install_libltc.sh
- export PATH=$PATH:/usr/local/opt/qt5/bin
- export JOKER_RELEASE_PATH=$HOME
- export TESTS_RELEASE_PATH=$HOME
- eval "$(pyenv init -)"

script:
- qmake -v
- qmake all.pro
- make
- cd tests/AutoTest
- ./AutoTest
- cd ../..
- "./scripts/doxygen.sh"
- "./scripts/uncrustify.sh"
after_success:
- coveralls --exclude /usr/local -E .+/moc_.+ -E .+/ui_.+ -E .+\.app
- "./scripts/update-gh-pages.sh"
after_failure:
- curl --form "file=@tests/AutoTest/graphicStripTestResult.bmp" http://phonations.com/feedback/serv.php
- curl --form "file=@tests/AutoTest/swensonTestResult.bmp" http://phonations.com/feedback/serv.php
- curl --form "file=@tests/AutoTest/arialTestResult.bmp" http://phonations.com/feedback/serv.php
- curl --form "file=@tests/AutoTest/bedizenTestResult.bmp" http://phonations.com/feedback/serv.php
- curl --form "file=@tests/AutoTest/weblysleekuilTestResult.bmp" http://phonations.com/feedback/serv.php
notifications:
  flowdock:
    secure: CnvMZuPXcFS6FQ17QYgtWsp9GUTbidjulsmpzbVh9S2zN2xVjGEMKe8KafPa55ugFYbYudCt7w20+wJO4OomYFQxgKAtJuGHZQ9jIfv0vl2sAcuzdaJY6aCFDtL4DFpAjGp8qwkZ0Mtx1xFgqyMcF/8eHfQm7bGO+ahmI5f9Jbc=
  email: false
env:
  global:
    secure: StCptdbX5mPsWDLvwtRS8R0IP2t0ZaPUpRHtnVQbooMyskwWHOiM809iGFoUNyvsZQiPl/0psWjlpXpWm+NBmChj/ADksx9PhFg8WKya3uTLQ2bJkGo9dtW7y1BQ38kDpqrKVjn1zTKF1lZvd3+09KzNmmjAAcoxlD6rqssP7Rw=
